### ISSUE TITLE
Route "/assets" is not appropriate

### ISSUE THREAD

**Issue by lethe2211** [jeetchris/elite_ams#2]
When I accessed http://localhost:3000/assets/new after staring the server, I found that I could not add a new asset because the error message "Method Not Allowed" was displayed.

I think that the reason of this error may be the name of route "/assets."
"assets" is used as a reserved word in Rails.
So if we want to use this route, we have to modify this into another name.

**Comment by jeetchris** [comment]
Yes, the problem is the name of the route.
Anyway, deleted the unnecessary CRUD in b28823a7381416dd019c25c837aa36e85eeb1ab1.
